steps:
    - name: hashicorp/terraform:1.13.0
      id: terraform-fmt
      entrypoint: sh
      args:
          - -c
          - |
              terraform fmt -recursive | tee /workspace/terraform-fmt.log
      dir: "terraform"

    - name: hashicorp/terraform:1.13.0
      id: "terraform-init"
      entrypoint: sh
      args:
          - -c
          - |
              terraform init -backend-config=bucket=levelup-group4-terraform-state \
                -input=false \
              | tee /workspace/terraform-init.log
      dir: "terraform"

    - name: hashicorp/terraform:1.13.0
      id: terraform-validate
      entrypoint: sh
      args:
          - -c
          - |
              terraform validate | tee /workspace/terraform-validate.log
      dir: "terraform"

    - name: gcr.io/cloud-builders/git
      id: "detect-pr-number"
      entrypoint: bash
      args:
          - -c
          - |
              PR_NUMBER=$(git log -1 --pretty=%s | sed -n 's/.*#\([0-9]\+\).*/\1/p')
              if [ -z "${PR_NUMBER}" ]; then
                  echo "Unable to detect PR number for commit ${COMMIT_SHA}" >&2
                  exit 1
              fi
              echo -n "${PR_NUMBER}" > /workspace/pr-number.txt

    - name: gcr.io/cloud-builders/gsutil
      id: "download-tfplan"
      entrypoint: bash
      args:
          - -c
          - |
              PR_NUMBER=$(cat /workspace/pr-number.txt)
              gsutil cp gs://levelup-group4-terraform-state/plans/pr-${PR_NUMBER}.tfplan terraform/tfplan

    - name: hashicorp/terraform:1.13.0
      id: "terraform-apply"
      entrypoint: sh
      args:
          - -c
          - |
              terraform apply -input=false -auto-approve tfplan \
              | tee /workspace/terraform-apply.log
      dir: "terraform"

    - name: gcr.io/cloud-builders/gsutil
      id: "cleanup-tfplan"
      entrypoint: bash
      args:
          - -c
          - |
              PR_NUMBER=$(cat /workspace/pr-number.txt)
              gsutil rm -f gs://levelup-group4-terraform-state/plans/pr-${PR_NUMBER}.tfplan

options:
    logging: CLOUD_LOGGING_ONLY
