steps:
    - name: hashicorp/terraform:1.13.0
      id: terraform-fmt
      entrypoint: sh
      args:
          - -c
          - |
              terraform fmt -recursive | tee /workspace/terraform-fmt.log
      dir: "terraform"

    - name: hashicorp/terraform:1.13.0
      id: "terraform-init"
      entrypoint: sh
      args:
          - -c
          - |
              terraform init -backend-config=bucket=levelup-group4-terraform-state \
                -input=false \
              | tee /workspace/terraform-init.log
      dir: "terraform"

    - name: hashicorp/terraform:1.13.0
      id: terraform-validate
      entrypoint: sh
      args:
          - -c
          - |
              terraform validate | tee /workspace/terraform-validate.log
      dir: "terraform"

    - name: gcr.io/cloud-builders/gsutil
      id: "download-tfplan"
      args:
          - cp
          - gs://levelup-group4-terraform-state/plans/${SHORT_SHA}.tfplan
          - tfplan
      dir: "terraform"

    - name: hashicorp/terraform:1.13.0
      id: "terraform-apply"
      entrypoint: sh
      args:
          - -c
          - |
              terraform apply -input=false -auto-approve tfplan \
              | tee /workspace/terraform-apply.log
      dir: "terraform"

    - name: gcr.io/cloud-builders/gsutil
      id: "cleanup-tfplan"
      args:
          - rm
          - -f
          - gs://levelup-group4-terraform-state/plans/${SHORT_SHA}.tfplan
      dir: "terraform"

options:
    logging: CLOUD_LOGGING_ONLY
