steps:
    # Terraform initialization
    - name: hashicorp/terraform:1.13.0
      id: "terraform-init"
      entrypoint: sh
      args:
          - -c
          - |
              terraform init -input=false \
              | tee /workspace/terraform-init.log
      dir: "terraform"

    # Terraform configuration validation
    - name: hashicorp/terraform:1.13.0
      id: terraform-validate
      entrypoint: sh
      args:
          - -c
          - |
              terraform validate | tee /workspace/terraform-validate.log
      dir: "terraform"

     # Generate Terraform plan using dev.tfvars
    - name: hashicorp/terraform:1.13.0
      id: "terraform-plan"
      entrypoint: sh
      args:
          - -c
          - |
              terraform plan \
                -var-file=tfvars/dev.tfvars \
                -out=tfplan \
                -input=false | tee /workspace/terraform-plan.log
      dir: "terraform"

    # Upload Terraform plan to GCS
    - name: gcr.io/cloud-builders/gsutil
      id: "upload-tfplan"
      entrypoint: bash
      args:
          - -c
          - |
              gsutil cp tfplan gs://levelup-group4-terraform-state/plans/default.tfplan
      dir: "terraform"

options:
    # Log to Cloud Logging
    logging: CLOUD_LOGGING_ONLY
