project_id         = "terraformgroup4"
project_name       = "levelup"
region             = "us-central1"
env                = "dev"
cidr_block         = "10.0.1.0/27"
notification_email = "ursz.kam@gmail.com"
